import oracledb
import os
# Path to your extracted wallet directory
WALLET_PATH = os.path.dirname(os.path.abspath(__file__))

# TNS name of your service from tnsnames.ora (usually ends with _high, _low, or _tp)
SERVICE_NAME = "m04vxfqnjt7h6fh0_high"

# Credentials from OCI when setting up DB user
DB_USER = "admin"
DB_PASSWORD = "Welcome_123#"

# Initialize thin mode with wallet
#oracledb.init_oracle_client(lib_dir=None)  # Set lib_dir only for thick mode; None enables thin mode
#oracledb.init_oracle_client(lib_dir=None)  # Set lib_dir only for thick mode; None enables thin mode

connection = oracledb.connect(
    user=DB_USER,
    password=DB_PASSWORD,
    dsn=f"{SERVICE_NAME}",
    config_dir=WALLET_PATH,
    wallet_location=WALLET_PATH,
    wallet_password=None  # Only needed if you set a wallet password
)

print("Connected to Oracle Autonomous Database.")

# Create a sample table
cursor = connection.cursor()
# cursor.execute("""
# CREATE TABLE customers (
#     id NUMBER GENERATED BY DEFAULT AS IDENTITY,
#     name VARCHAR2(100),
#     city VARCHAR2(100),
#     email VARCHAR2(100),
#     PRIMARY KEY (id)
# );
# 
# INSERT INTO customers (name, city, email) VALUES
# ('Amit Sharma', 'Mumbai', 'amit@example.com'),
# ('Neha Mehta', 'Delhi', 'neha@example.com'),
# ('Rahul Joshi', 'Mumbai', 'rahul@example.com');
# 
# COMMIT;
# """)
# print("Table created successfully.")

with open("data/sample_schema.sql", "r") as f:
    sql = f.read()

# Split on semicolons (;) but avoid empty statements
for stmt in sql.split(";"):
    stmt = stmt.strip()
    if stmt:
        try:
            cursor.execute(stmt)
            print(f"✅ Executed: {stmt[:50]}...")
        except oracledb.DatabaseError as e:
            print(f"❌ Error executing:\n{stmt}\n{e}")

cursor.close()
connection.close()
