CREATE TABLE customers (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(100),
    city VARCHAR2(100),
    email VARCHAR2(100),
    PRIMARY KEY (id)
);

INSERT INTO customers (name, city, email) VALUES
('Amit Sharma', 'Mumbai', 'amit@example.com'),
('Neha Mehta', 'Delhi', 'neha@example.com'),
('Rahul Joshi', 'Mumbai', 'rahul@example.com');

CREATE TABLE documents (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(200),
    content CLOB,
    embedding VECTOR(384),  -- or 768 or 1536 depending on your embedding model
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE DIRECTORY model_dir AS '/Users/sadanandupase/Downloads';
GRANT READ ON DIRECTORY model_dir TO ADMIN;


BEGIN
  DBMS_VECTOR.LOAD_ONNX_MODEL(
    directory   => '/Users/sadanandupase/Downloads',
    file_name   => 'model.onnx',
    model_name  => 'nomic_embed_model'
    
  );
END;
/
