CREATE TABLE customers (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(100),
    city VARCHAR2(100),
    email VARCHAR2(100),
    PRIMARY KEY (id)
);

INSERT INTO customers (name, city, email) VALUES
('Amit Sharma', 'Mumbai', 'amit@example.com'),
('Neha Mehta', 'Delhi', 'neha@example.com'),
('Rahul Joshi', 'Mumbai', 'rahul@example.com');


CREATE TABLE documents (
  id        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title     VARCHAR2(200),
  content   CLOB,
  embedding VECTOR(1536, FLOAT32)  -- ✅ Match your actual embedding size
);


EXEC DBMS_CLOUD_ADMIN.ENABLE_RESOURCE_PRINCIPAL();

BEGIN
  DBMS_CLOUD.GET_OBJECT(
    credential_name => 'OCI$RESOURCE_PRINCIPAL',
    directory_name  => 'DATA_PUMP_DIR',
    object_uri      => 'https://objectstorage.us-chicago-1.oraclecloud.com/n/axke9xehyrpc/b/ModelBucket/o/all_MiniLM_L12_v2.onnx'
  );
END;
/


BEGIN
  DBMS_VECTOR.LOAD_ONNX_MODEL(
    directory   => 'DATA_PUMP_DIR',
    file_name   => 'all_MiniLM_L12_v2.onnx',
    model_name  => 'all_MiniLM_L12_v2'
    
  );
END;
/

SELECT DBMS_VECTOR.UTL_TO_EMBEDDING(
         'User reported payment failure at checkout',
         JSON('{"provider":"database","model":"all_MiniLM_L12_v2"}')
       ) AS vec
FROM dual;